<font color='Orange'> <h2> Extracting City & Country from Longitude and Latitude  </h2> </font>
#### By: 
- Hemanth Mydugolam

#### Note: 
The hotel addresses is taken from the Europe Hotels data.

In [2]:
# Install the geopy package if not available in your library list
#!pip install geopy

In [1]:
# import module
from geopy.geocoders import Nominatim

# initialize Nominatim API
geolocator = Nominatim(user_agent="geoapiExercises")

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("Hotel_Addresses_only.csv")

In [5]:
df.head()

                                       Hotel_Address        lat       lng
0   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...  52.360576  4.915968
1  1 15 Templeton Place Earl s Court Kensington a...  51.491888 -0.194971
2  1 2 Serjeant s Inn Fleet Street City of London...  51.513734 -0.108751
3  1 3 Queens Garden Westminster Borough London W...  51.514218 -0.180903
4    1 3 Rue d Argentine 16th arr 75116 Paris France  48.874348  2.289733

In [6]:
df['City'] = ""
df['Country'] = ""

In [7]:
df.head()

,Hotel_Address,lat,lng,City,Country
0,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,52.360576,4.915968,,
1,1 15 Templeton Place Earl s Court Kensington a...,51.491888,-0.194971,,
2,1 2 Serjeant s Inn Fleet Street City of London...,51.513734,-0.108751,,
3,1 3 Queens Garden Westminster Borough London W...,51.514218,-0.180903,,
4,1 3 Rue d Argentine 16th arr 75116 Paris France,48.874348,2.289733,,

In [8]:
import pandas as pd
from geopy.geocoders import Nominatim  # Make sure to install geopy: pip install geopy

# Sample DataFrame with latitude and longitude columns
df = pd.DataFrame(df)

# Create a geolocator
geolocator = Nominatim(user_agent="geo_locator")

# Loop through each row in the DataFrame
for index, row in df.iterrows():
    latitude = str(row['lat'])
    longitude = str(row['lng'])

    # Get location information
    location = geolocator.reverse(latitude + "," + longitude)
    address = location.raw.get('address', {})

    # Extract city and country
    city = address.get('city', '')
    country = address.get('country', '')

    # Update the DataFrame with city information
    df.at[index, 'City'] = city
    df.at[index, 'Country'] = country

    # Print the results
    print(f'Row {index + 1}:')
    #print('Latitude:', latitude)
    #print('Longitude:', longitude)
    #print('City:', city)
    #print('Country:', country)

# Display the updated DataFrame
print("Updated DataFrame:")
print(df)

Row 1:
Row 2:
Row 3:
Row 4:
Row 5:
Row 6:
Row 7:
Row 8:
Row 9:
Row 10:
Row 11:
Row 12:
Row 13:
Row 14:
Row 15:
Row 16:
Row 17:
Row 18:
Row 19:
Row 20:
Row 21:
Row 22:
Row 23:
Row 24:
Row 25:
Row 26:
Row 27:
Row 28:
Row 29:
Row 30:
Row 31:
Row 32:
Row 33:
Row 34:
Row 35:
Row 36:
Row 37:
Row 38:
Row 39:
Row 40:
Row 41:
Row 42:
Row 43:
Row 44:
Row 45:
Row 46:
Row 47:
Row 48:
Row 49:
Row 50:
Row 51:
Row 52:
Row 53:
Row 54:
Row 55:
Row 56:
Row 57:
Row 58:
Row 59:
Row 60:
Row 61:
Row 62:
Row 63:
Row 64:
Row 65:
Row 66:
Row 67:
Row 68:
Row 69:
Row 70:
Row 71:
Row 72:
Row 73:
Row 74:
Row 75:
Row 76:
Row 77:
Row 78:
Row 79:
Row 80:
Row 81:
Row 82:
Row 83:
Row 84:
Row 85:
Row 86:
Row 87:
Row 88:
Row 89:
Row 90:
Row 91:
Row 92:
Row 93:
Row 94:
Row 95:
Row 96:
Row 97:
Row 98:
Row 99:
Row 100:
Row 101:
Row 102:
Row 103:
Row 104:
Row 105:
Row 106:
Row 107:
Row 108:
Row 109:
Row 110:
Row 111:
Row 112:
Row 113:
Row 114:
Row 115:
Row 116:
Row 117:
Row 118:
Row 119:
Row 120:
Row 121:
Row 122:
Row 123:
Row 124:
Row 125:
Row 126:
Row 127:
Row 128:
Row 129:
Row 130:
Row 131:
Row 132:
Row 133:
Row 134:
Row 135:
Row 136:
Row 137:
Row 138:
Row 139:
Row 140:
Row 141:
Row 142:
Row 143:
Row 144:
Row 145:
Row 146:
Row 147:
Row 148:
Row 149:
Row 150:
Row 151:
Row 152:
Row 153:
Row 154:
Row 155:
Row 156:
Row 157:
Row 158:
Row 159:
Row 160:
Row 161:
Row 162:
Row 163:
Row 164:
Row 165:
Row 166:
Row 167:
Row 168:
Row 169:
Row 170:
Row 171:
Row 172:
Row 173:
Row 174:
Row 175:
Row 176:
Row 177:
Row 178:
Row 179:
Row 180:
Row 181:
Row 182:
Row 183:
Row 184:
Row 185:
Row 186:
Row 187:
Row 188:
Row 189:
Row 190:
Row 191:
Row 192:
Row 193:
Row 194:
Row 195:
Row 196:
Row 197:
Row 198:
Row 199:
Row 200:
Row 201:
Row 202:
Row 203:
Row 204:
Row 205:
Row 206:
Row 207:
Row 208:
Row 209:
Row 210:
Row 211:
Row 212:
Row 213:
Row 214:
Row 215:
Row 216:
Row 217:
Row 218:
Row 219:
Row 220:
Row 221:
Row 222:
Row 223:
Row 224:
Row 225:
Row 226:
Row 227:
Row 228:
Row 229:
Row 230:
Row 231:
Row 232:
Row 233:
Row 234:
Row 235:
Row 236:
Row 237:
Row 238:
Row 239:
Row 240:
Row 241:
Row 242:
Row 243:
Row 244:
Row 245:
Row 246:
Row 247:
Row 248:
Row 249:
Row 250:
Row 251:
Row 252:
Row 253:
Row 254:
Row 255:
Row 256:
Row 257:
Row 258:
Row 259:
Row 260:
Row 261:
Row 262:
Row 263:
Row 264:
Row 265:
Row 266:
Row 267:
Row 268:
Row 269:
Row 270:
Row 271:
Row 272:
Row 273:
Row 274:
Row 275:
Row 276:
Row 277:
Row 278:
Row 279:
Row 280:
Row 281:
Row 282:
Row 283:
Row 284:
Row 285:
Row 286:
Row 287:
Row 288:
Row 289:
Row 290:
Row 291:
Row 292:
Row 293:
Row 294:
Row 295:
Row 296:
Row 297:
Row 298:
Row 299:
Row 300:
Row 301:
Row 302:
Row 303:
Row 304:
Row 305:
Row 306:
Row 307:
Row 308:
Row 309:
Row 310:
Row 311:
Row 312:
Row 313:
Row 314:
Row 315:
Row 316:
Row 317:
Row 318:
Row 319:
Row 320:
Row 321:
Row 322:
Row 323:
Row 324:
Row 325:
Row 326:
Row 327:
Row 328:
Row 329:
Row 330:
Row 331:
Row 332:
Row 333:
Row 334:
Row 335:
Row 336:
Row 337:
Row 338:
Row 339:
Row 340:
Row 341:
Row 342:
Row 343:
Row 344:
Row 345:
Row 346:
Row 347:
Row 348:
Row 349:
Row 350:
Row 351:
Row 352:
Row 353:
Row 354:
Row 355:
Row 356:
Row 357:
Row 358:
Row 359:
Row 360:
Row 361:
Row 362:
Row 363:
Row 364:
Row 365:
Row 366:
Row 367:
Row 368:
Row 369:
Row 370:
Row 371:
Row 372:
Row 373:
Row 374:
Row 375:
Row 376:
Row 377:
Row 378:
Row 379:
Row 380:
Row 381:
Row 382:
Row 383:
Row 384:
Row 385:
Row 386:
Row 387:
Row 388:
Row 389:
Row 390:
Row 391:
Row 392:
Row 393:
Row 394:
Row 395:
Row 396:
Row 397:
Row 398:
Row 399:
Row 400:
Row 401:
Row 402:
Row 403:
Row 404:
Row 405:
Row 406:
Row 407:
Row 408:
Row 409:
Row 410:
Row 411:
Row 412:
Row 413:
Row 414:
Row 415:
Row 416:
Row 417:
Row 418:
Row 419:
Row 420:
Row 421:
Row 422:
Row 423:
Row 424:
Row 425:
Row 426:
Row 427:
Row 428:
Row 429:
Row 430:
Row 431:
Row 432:
Row 433:
Row 434:
Row 435:
Row 436:
Row 437:
Row 438:
Row 439:
Row 440:
Row 441:
Row 442:
Row 443:
Row 444:
Row 445:
Row 446:
Row 447:
Row 448:
Row 449:
Row 450:
Row 451:
Row 452:
Row 453:
Row 454:
Row 455:
Row 456:
Row 457:
Row 458:
Row 459:
Row 460:
Row 461:
Row 462:
Row 463:
Row 464:
Row 465:
Row 466:
Row 467:
Row 468:
Row 469:
Row 470:
Row 471:
Row 472:
Row 473:
Row 474:
Row 475:
Row 476:
Row 477:
Row 478:
Row 479:
Row 480:
Row 481:
Row 482:
Row 483:
Row 484:
Row 485:
Row 486:
Row 487:
Row 488:
Row 489:
Row 490:
Row 491:
Row 492:
Row 493:
Row 494:
Row 495:
Row 496:
Row 497:
Row 498:
Row 499:
Row 500:
Row 501:
Row 502:
Row 503:
Row 504:
Row 505:
Row 506:
Row 507:
Row 508:
Row 509:
Row 510:
Row 511:
Row 512:
Row 513:
Row 514:
Row 515:
Row 516:
Row 517:
Row 518:
Row 519:
Row 520:
Row 521:
Row 522:
Row 523:
Row 524:
Row 525:
Row 526:
Row 527:
Row 528:
Row 529:
Row 530:
Row 531:
Row 532:
Row 533:
Row 534:
Row 535:
Row 536:
Row 537:
Row 538:
Row 539:
Row 540:
Row 541:
Row 542:
Row 543:
Row 544:
Row 545:
Row 546:
Row 547:
Row 548:
Row 549:
Row 550:
Row 551:
Row 552:
Row 553:
Row 554:
Row 555:
Row 556:
Row 557:
Row 558:
Row 559:
Row 560:
Row 561:
Row 562:
Row 563:
Row 564:
Row 565:
Row 566:
Row 567:
Row 568:
Row 569:
Row 570:
Row 571:
Row 572:
Row 573:
Row 574:
Row 575:
Row 576:
Row 577:
Row 578:
Row 579:
Row 580:
Row 581:
Row 582:
Row 583:
Row 584:
Row 585:
Row 586:
Row 587:
Row 588:
Row 589:
Row 590:
Row 591:
Row 592:
Row 593:
Row 594:
Row 595:
Row 596:
Row 597:
Row 598:
Row 599:
Row 600:
Row 601:
Row 602:
Row 603:
Row 604:
Row 605:
Row 606:
Row 607:
Row 608:
Row 609:
Row 610:
Row 611:
Row 612:
Row 613:
Row 614:
Row 615:
Row 616:
Row 617:
Row 618:
Row 619:
Row 620:
Row 621:
Row 622:
Row 623:
Row 624:
Row 625:
Row 626:
Row 627:
Row 628:
Row 629:
Row 630:
Row 631:
Row 632:
Row 633:
Row 634:
Row 635:
Row 636:
Row 637:
Row 638:
Row 639:
Row 640:
Row 641:
Row 642:
Row 643:
Row 644:
Row 645:
Row 646:
Row 647:
Row 648:
Row 649:
Row 650:
Row 651:
Row 652:
Row 653:
Row 654:
Row 655:
Row 656:
Row 657:
Row 658:
Row 659:
Row 660:
Row 661:
Row 662:
Row 663:
Row 664:
Row 665:
Row 666:
Row 667:
Row 668:
Row 669:
Row 670:
Row 671:
Row 672:
Row 673:
Row 674:
Row 675:
Row 676:
Row 677:
Row 678:
Row 679:
Row 680:
Row 681:
Row 682:
Row 683:
Row 684:
Row 685:
Row 686:
Row 687:
Row 688:
Row 689:
Row 690:
Row 691:
Row 692:
Row 693:
Row 694:
Row 695:
Row 696:
Row 697:
Row 698:
Row 699:
Row 700:
Row 701:
Row 702:
Row 703:
Row 704:
Row 705:
Row 706:
Row 707:
Row 708:
Row 709:
Row 710:
Row 711:
Row 712:
Row 713:
Row 714:
Row 715:
Row 716:
Row 717:
Row 718:
Row 719:
Row 720:
Row 721:
Row 722:
Row 723:
Row 724:
Row 725:
Row 726:
Row 727:
Row 728:
Row 729:
Row 730:
Row 731:
Row 732:
Row 733:
Row 734:
Row 735:
Row 736:
Row 737:
Row 738:
Row 739:
Row 740:
Row 741:
Row 742:
Row 743:
Row 744:
Row 745:
Row 746:
Row 747:
Row 748:
Row 749:
Row 750:
Row 751:
Row 752:
Row 753:
Row 754:
Row 755:
Row 756:
Row 757:
Row 758:
Row 759:
Row 760:
Row 761:
Row 762:
Row 763:
Row 764:
Row 765:
Row 766:
Row 767:
Row 768:
Row 769:
Row 770:
Row 771:
Row 772:
Row 773:
Row 774:
Row 775:
Row 776:
Row 777:
Row 778:
Row 779:
Row 780:
Row 781:
Row 782:
Row 783:
Row 784:
Row 785:
Row 786:
Row 787:
Row 788:
Row 789:
Row 790:
Row 791:
Row 792:
Row 793:
Row 794:
Row 795:
Row 796:
Row 797:
Row 798:
Row 799:
Row 800:
Row 801:
Row 802:
Row 803:
Row 804:
Row 805:
Row 806:
Row 807:
Row 808:
Row 809:
Row 810:
Row 811:
Row 812:
Row 813:
Row 814:
Row 815:
Row 816:
Row 817:
Row 818:
Row 819:
Row 820:
Row 821:
Row 822:
Row 823:
Row 824:
Row 825:
Row 826:
Row 827:
Row 828:
Row 829:
Row 830:
Row 831:
Row 832:
Row 833:
Row 834:
Row 835:
Row 836:
Row 837:
Row 838:
Row 839:
Row 840:
Row 841:
Row 842:
Row 843:
Row 844:
Row 845:
Row 846:
Row 847:
Row 848:
Row 849:
Row 850:
Row 851:
Row 852:
Row 853:
Row 854:
Row 855:
Row 856:
Row 857:
Row 858:
Row 859:
Row 860:
Row 861:
Row 862:
Row 863:
Row 864:
Row 865:
Row 866:
Row 867:
Row 868:
Row 869:
Row 870:
Row 871:
Row 872:
Row 873:
Row 874:
Row 875:
Row 876:
Row 877:
Row 878:
Row 879:
Row 880:
Row 881:
Row 882:
Row 883:
Row 884:
Row 885:
Row 886:
Row 887:
Row 888:
Row 889:
Row 890:
Row 891:
Row 892:
Row 893:
Row 894:
Row 895:
Row 896:
Row 897:
Row 898:
Row 899:
Row 900:
Row 901:
Row 902:
Row 903:
Row 904:
Row 905:
Row 906:
Row 907:
Row 908:
Row 909:
Row 910:
Row 911:
Row 912:
Row 913:
Row 914:
Row 915:
Row 916:
Row 917:
Row 918:
Row 919:
Row 920:
Row 921:
Row 922:
Row 923:

Row 924:
Row 925:
Row 926:
Row 927:
Row 928:
Row 929:
Row 930:
Row 931:
Row 932:
Row 933:
Row 934:
Row 935:
Row 936:
Row 937:
Row 938:
Row 939:
Row 940:
Row 941:
Row 942:
Row 943:
Row 944:
Row 945:
Row 946:
Row 947:
Row 948:
Row 949:
Row 950:
Row 951:
Row 952:
Row 953:
Row 954:
Row 955:
Row 956:
Row 957:
Row 958:
Row 959:
Row 960:
Row 961:
Row 962:
Row 963:
Row 964:
Row 965:
Row 966:
Row 967:
Row 968:
Row 969:
Row 970:
Row 971:
Row 972:
Row 973:
Row 974:
Row 975:
Row 976:
Row 977:
Row 978:
Row 979:
Row 980:
Row 981:
Row 982:
Row 983:
Row 984:
Row 985:
Row 986:
Row 987:
Row 988:
Row 989:
Row 990:
Row 991:
Row 992:
Row 993:
Row 994:
Row 995:
Row 996:
Row 997:
Row 998:
Row 999:
Row 1000:
Row 1001:
Row 1002:
Row 1003:
Row 1004:
Row 1005:
Row 1006:
Row 1007:
Row 1008:
Row 1009:
Row 1010:
Row 1011:
Row 1012:
Row 1013:
Row 1014:
Row 1015:
Row 1016:
Row 1017:
Row 1018:
Row 1019:
Row 1020:
Row 1021:
Row 1022:
Row 1023:
Row 1024:
Row 1025:
Row 1026:
Row 1027:
Row 1028:
Row 1029:
Row 1030:
Row 1031:
Row 1032:
Row 1033:
Row 1034:
Row 1035:
Row 1036:
Row 1037:
Row 1038:
Row 1039:
Row 1040:
Row 1041:
Row 1042:
Row 1043:
Row 1044:
Row 1045:
Row 1046:
Row 1047:
Row 1048:
Row 1049:
Row 1050:
Row 1051:
Row 1052:
Row 1053:
Row 1054:
Row 1055:
Row 1056:
Row 1057:
Row 1058:
Row 1059:
Row 1060:
Row 1061:
Row 1062:
Row 1063:
Row 1064:
Row 1065:
Row 1066:
Row 1067:
Row 1068:
Row 1069:
Row 1070:
Row 1071:
Row 1072:
Row 1073:
Row 1074:
Row 1075:
Row 1076:
Row 1077:
Row 1078:
Row 1079:
Row 1080:
Row 1081:
Row 1082:
Row 1083:
Row 1084:
Row 1085:
Row 1086:
Row 1087:
Row 1088:
Row 1089:
Row 1090:
Row 1091:
Row 1092:
Row 1093:
Row 1094:
Row 1095:
Row 1096:
Row 1097:
Row 1098:
Row 1099:
Row 1100:
Row 1101:
Row 1102:
Row 1103:
Row 1104:
Row 1105:
Row 1106:
Row 1107:
Row 1108:
Row 1109:
Row 1110:
Row 1111:
Row 1112:
Row 1113:
Row 1114:
Row 1115:
Row 1116:
Row 1117:
Row 1118:
Row 1119:
Row 1120:
Row 1121:
Row 1122:
Row 1123:
Row 1124:
Row 1125:
Row 1126:
Row 1127:
Row 1128:
Row 1129:
Row 1130:
Row 1131:
Row 1132:
Row 1133:
Row 1134:
Row 1135:
Row 1136:
Row 1137:
Row 1138:
Row 1139:
Row 1140:
Row 1141:
Row 1142:
Row 1143:
Row 1144:
Row 1145:
Row 1146:
Row 1147:
Row 1148:
Row 1149:
Row 1150:
Row 1151:
Row 1152:
Row 1153:
Row 1154:
Row 1155:
Row 1156:
Row 1157:
Row 1158:
Row 1159:
Row 1160:
Row 1161:
Row 1162:
Row 1163:
Row 1164:
Row 1165:
Row 1166:
Row 1167:
Row 1168:
Row 1169:
Row 1170:
Row 1171:
Row 1172:
Row 1173:
Row 1174:
Row 1175:
Row 1176:
Row 1177:
Row 1178:
Row 1179:
Row 1180:
Row 1181:
Row 1182:
Row 1183:
Row 1184:
Row 1185:
Row 1186:
Row 1187:
Row 1188:
Row 1189:
Row 1190:
Row 1191:
Row 1192:
Row 1193:
Row 1194:
Row 1195:
Row 1196:
Row 1197:
Row 1198:
Row 1199:
Row 1200:
Row 1201:
Row 1202:
Row 1203:
Row 1204:
Row 1205:
Row 1206:
Row 1207:
Row 1208:
Row 1209:
Row 1210:
Row 1211:
Row 1212:
Row 1213:
Row 1214:
Row 1215:
Row 1216:
Row 1217:
Row 1218:
Row 1219:
Row 1220:
Row 1221:
Row 1222:
Row 1223:
Row 1224:
Row 1225:
Row 1226:
Row 1227:
Row 1228:
Row 1229:
Row 1230:
Row 1231:
Row 1232:
Row 1233:
Row 1234:
Row 1235:
Row 1236:
Row 1237:
Row 1238:
Row 1239:
Row 1240:
Row 1241:
Row 1242:
Row 1243:
Row 1244:
Row 1245:
Row 1246:
Row 1247:
Row 1248:
Row 1249:
Row 1250:
Row 1251:
Row 1252:
Row 1253:
Row 1254:
Row 1255:
Row 1256:
Row 1257:
Row 1258:
Row 1259:
Row 1260:
Row 1261:
Row 1262:
Row 1263:
Row 1264:
Row 1265:
Row 1266:
Row 1267:
Row 1268:
Row 1269:
Row 1270:
Row 1271:
Row 1272:
Row 1273:
Row 1274:
Row 1275:
Row 1276:
Row 1277:
Row 1278:
Row 1279:
Row 1280:
Row 1281:
Row 1282:
Row 1283:
Row 1284:
Row 1285:
Row 1286:
Row 1287:
Row 1288:
Row 1289:
Row 1290:
Row 1291:
Row 1292:
Row 1293:
Row 1294:
Row 1295:
Row 1296:
Row 1297:
Row 1298:
Row 1299:
Row 1300:
Row 1301:
Row 1302:
Row 1303:
Row 1304:
Row 1305:
Row 1306:
Row 1307:
Row 1308:
Row 1309:
Row 1310:
Row 1311:
Row 1312:
Row 1313:
Row 1314:
Row 1315:
Row 1316:
Row 1317:
Row 1318:
Row 1319:
Row 1320:
Row 1321:
Row 1322:
Row 1323:
Row 1324:
Row 1325:
Row 1326:
Row 1327:
Row 1328:
Row 1329:
Row 1330:
Row 1331:
Row 1332:
Row 1333:
Row 1334:
Row 1335:
Row 1336:
Row 1337:
Row 1338:
Row 1339:
Row 1340:
Row 1341:
Row 1342:
Row 1343:
Row 1344:
Row 1345:
Row 1346:
Row 1347:
Row 1348:
Row 1349:
Row 1350:
Row 1351:
Row 1352:
Row 1353:
Row 1354:
Row 1355:
Row 1356:
Row 1357:
Row 1358:
Row 1359:
Row 1360:
Row 1361:
Row 1362:
Row 1363:
Row 1364:
Row 1365:
Row 1366:
Row 1367:
Row 1368:
Row 1369:
Row 1370:
Row 1371:
Row 1372:
Row 1373:
Row 1374:
Row 1375:
Row 1376:
Row 1377:
Row 1378:
Row 1379:
Row 1380:
Row 1381:
Row 1382:
Row 1383:
Row 1384:
Row 1385:
Row 1386:
Row 1387:
Row 1388:
Row 1389:
Row 1390:
Row 1391:
Row 1392:
Row 1393:
Row 1394:
Row 1395:
Row 1396:
Row 1397:
Row 1398:
Row 1399:
Row 1400:
Row 1401:
Row 1402:
Row 1403:
Row 1404:
Row 1405:
Row 1406:
Row 1407:
Row 1408:
Row 1409:
Row 1410:
Row 1411:
Row 1412:
Row 1413:
Row 1414:
Row 1415:
Row 1416:
Row 1417:
Row 1418:
Row 1419:
Row 1420:
Row 1421:
Row 1422:
Row 1423:
Row 1424:
Row 1425:
Row 1426:
Row 1427:
Row 1428:
Row 1429:
Row 1430:
Row 1431:
Row 1432:
Row 1433:
Row 1434:
Row 1435:
Row 1436:
Row 1437:
Row 1438:
Row 1439:
Row 1440:
Row 1441:
Row 1442:
Row 1443:
Row 1444:
Row 1445:
Row 1446:
Row 1447:
Row 1448:
Row 1449:
Row 1450:
Row 1451:
Row 1452:
Row 1453:
Row 1454:
Row 1455:
Row 1456:
Row 1457:
Row 1458:
Row 1459:
Row 1460:
Row 1461:
Row 1462:
Row 1463:
Row 1464:
Row 1465:
Row 1466:
Row 1467:
Row 1468:
Row 1469:
Row 1470:
Row 1471:
Row 1472:
Row 1473:
Row 1474:
Row 1475:
Row 1476:
Row 1477:
Row 1478:
Row 1479:
Row 1480:
Row 1481:
Row 1482:
Row 1483:
Row 1484:
Row 1485:
Row 1486:
Row 1487:
Row 1488:
Row 1489:
Row 1490:
Row 1491:
Row 1492:
Row 1493:
Updated DataFrame:
                                          Hotel_Address        lat        lng  \
0      s Gravesandestraat 55 Oost 1092 AA Amsterdam ...  52.360576   4.915968
1     1 15 Templeton Place Earl s Court Kensington a...  51.491888  -0.194971
2     1 2 Serjeant s Inn Fleet Street City of London...  51.513734  -0.108751
3     1 3 Queens Garden Westminster Borough London W...  51.514218  -0.180903
4       1 3 Rue d Argentine 16th arr 75116 Paris France  48.874348   2.289733
...                                                 ...        ...        ...
1488  Wiedner Hauptstra e 44 04 Wieden 1040 Vienna A...  48.193523  16.366915
1489  Wildpretmarkt 5 01 Innere Stadt 1010 Vienna Au...  48.210447  16.371578
1490  Wilton Place Knightsbridge Westminster Borough...  51.502091  -0.157779
1491  Wrights Lane Kensington and Chelsea London W8 ...  51.499981  -0.192879
1492  Wurzbachgasse 21 15 Rudolfsheim F nfhaus 1150 ...  48.203745  16.335677

                City         Country
0          Amsterdam       Nederland
1             London  United Kingdom
2     City of London  United Kingdom
3             London  United Kingdom
4              Paris          France
...              ...             ...
1488            Wien      Österreich
1489            Wien      Österreich
1490          London  United Kingdom
1491          London  United Kingdom
1492            Wien      Österreich

[1493 rows x 5 columns]

In [9]:
df.head()

,Hotel_Address,lat,lng,City,Country
0,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,52.360576,4.915968,Amsterdam,Nederland
1,1 15 Templeton Place Earl s Court Kensington a...,51.491888,-0.194971,London,United Kingdom
2,1 2 Serjeant s Inn Fleet Street City of London...,51.513734,-0.108751,City of London,United Kingdom
3,1 3 Queens Garden Westminster Borough London W...,51.514218,-0.180903,London,United Kingdom
4,1 3 Rue d Argentine 16th arr 75116 Paris France,48.874348,2.289733,Paris,France

In [10]:
df['lat_updated'] = ""
df['lon_updated'] = ""

In [11]:
df['City'].unique()
df['City'].value_counts()

City
Paris                  455
London                 369
Barcelona              210
Milano                 162
Wien                   158
Amsterdam              105
City of London          16
City of Westminster     14
                         4
Name: count, dtype: int64

In [12]:
df.loc[df['City'] == '']

,Hotel_Address,lat,lng,City,Country,lat_updated,lon_updated
122,13 Rue Fran ois Ory 92120 Paris France,48.817808,2.329364,,France,,
473,36 38 Rue Du Moulin 92170 Paris France,48.826825,2.291203,,France,,
606,52 Rue Oradour sur Glane 15th arr 75015 Paris ...,48.830302,2.284287,,France,,
1266,Santa Rosa Esplugues 33 08950 Barcelona Spain,41.385472,2.101884,,España,,

In [17]:
df.to_csv("city_data.csv")

In [13]:
city_df = pd.read_csv("city_data.csv")

In [14]:
city_df.head()

,Unnamed: 0,Hotel_Address,lat,lng,City,Country,lat_updated,lon_updated
0,0,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,52.360576,4.915968,Amsterdam,Nederland,52.373080,4.892453
1,1,1 15 Templeton Place Earl s Court Kensington a...,51.491888,-0.194971,London,United Kingdom,51.489334,-0.144055
2,2,1 2 Serjeant s Inn Fleet Street City of London...,51.513734,-0.108751,City of London,United Kingdom,51.515618,-0.091998
3,3,1 3 Queens Garden Westminster Borough London W...,51.514218,-0.180903,London,United Kingdom,51.489334,-0.144055
4,4,1 3 Rue d Argentine 16th arr 75116 Paris France,48.874348,2.289733,Paris,France,48.853495,2.348391

In [15]:
dfg = city_df.groupby(by=["City", "lat_updated","lon_updated"]).size().reset_index(name="Hotel Count")
dfg

                  City  lat_updated  lon_updated  Hotel Count
0            Amsterdam    52.373080     4.892453          105
1            Barcelona    41.382894     2.177432          211
2       City of London    51.515618    -0.091998           16
3  City of Westminster    51.497321    -0.137149           14
4               London    51.489334    -0.144055          369
5               Milano    45.464194     9.189635          162
6                Paris    48.853495     2.348391          458
7                 Wien    48.208354    16.372504          158

In [16]:
city_data = dfg

In [17]:
city_data = city_data.rename(columns={'lat_updated': 'Latitude', 'lon_updated': 'Longitude'})

In [18]:
city_data.head()

                  City   Latitude  Longitude  Hotel Count
0            Amsterdam  52.373080   4.892453          105
1            Barcelona  41.382894   2.177432          211
2       City of London  51.515618  -0.091998           16
3  City of Westminster  51.497321  -0.137149           14
4               London  51.489334  -0.144055          369

In [19]:
import folium
from folium.plugins import MarkerCluster
from IPython.display import display

# Hypothetical data - Replace this with your actual data
city_data = {
    'City': ['Amsterdam', 'Barcelona', 'City of London', 'City of Westminster', 'London'],
    'Latitude': [52.373080, 41.382894, 51.515618,51.497321,51.489334],
    'Longitude': [4.892453, 2.177432, -0.091998,-0.137149,-0.144055],
    'HotelCount': [105, 211, 16, 14, 369]
}
fixed_radius = 10
# Create a Folium map centered around the first city
map_center = [city_data['Latitude'][0], city_data['Longitude'][0]]
my_map = folium.Map(location=map_center, zoom_start=5)

# Create a MarkerCluster layer
marker_cluster = MarkerCluster().add_to(my_map)

# Add markers for each city with hotel count as the radius
for i in range(len(city_data['City'])):
    folium.CircleMarker(
        location=[city_data['Latitude'][i], city_data['Longitude'][i]],
        radius=fixed_radius,
        color='red',
        fill=True,
        fill_color='red',
        fill_opacity=0.7,
        popup=f"{city_data['City'][i]} - {city_data['HotelCount'][i]} hotels"
    ).add_to(marker_cluster)

# Display the map directly in the notebook
display(my_map)

In [ ]:
import folium
from folium.plugins import MarkerCluster
from IPython.display import display

# Hypothetical data - Replace this with your actual data
city_data = {
    'City': ['City A', 'City B', 'City C'],
    'Latitude': [40.7128, 34.0522, 41.8781],
    'Longitude': [-74.0060, -118.2437, -87.6298],
    'HotelCount': [50, 30, 70]
}

# Create a Folium map centered around the first city
map_center = [city_data['Latitude'][0], city_data['Longitude'][0]]
my_map = folium.Map(location=map_center, zoom_start=5)

# Create a MarkerCluster layer
marker_cluster = MarkerCluster().add_to(my_map)

# Add markers for each city with hotel count as the radius
for i in range(len(city_data['City'])):
    folium.CircleMarker(
        location=[city_data['Latitude'][i], city_data['Longitude'][i]],
        radius=city_data['HotelCount'][i],
        color='red',
        fill=True,
        fill_color='red',
        fill_opacity=0.7,
        popup=f"{city_data['City'][i]} - {city_data['HotelCount'][i]} hotels"
    ).add_to(marker_cluster)

# Display the map directly in the notebook
display(my_map)

In [ ]:
import pandas as pd
from geopy.geocoders import Nominatim  # Make sure to install geopy: pip install geopy

# Sample DataFrame with a 'City' column
data_city = {'City': ['Paris', 'London', 'Berlin']}
df1 = pd.DataFrame(data_city)

# Create a geolocator
geolocator = Nominatim(user_agent="geo_locator")

# Loop through each row in the DataFrame
for index, row in df1.iterrows():
    city = row['City']

    # Get location information
    location = geolocator.geocode(city)

    # Update the DataFrame with latitude and longitude
    if location:
        df1.at[index, 'lat_updated'] = location.latitude
        df1.at[index, 'lon_updated'] = location.longitude
    else:
        print(f"Could not find coordinates for {city}")

# Display the updated DataFrame
print("Updated DataFrame:")
print(df1)

In [41]:
# Import the required library
from geopy.geocoders import Nominatim

# Initialize Nominatim API
geolocator = Nominatim(user_agent="MyApp")

location = geolocator.geocode("Stuttgart")

print("The latitude of the location is: ", location.latitude)
print("The longitude of the location is: ", location.longitude)

The latitude of the location is:  48.7784485
The longitude of the location is:  9.1800132

In [ ]:
#!pip install geopandas matplotlib

In [ ]:
import geopandas as gpd
import matplotlib.pyplot as plt

# Hypothetical data - Replace this with your actual data
city_data = {
    'City': ['City A', 'City B', 'City C'],
    'Latitude': [40.7128, 34.0522, 41.8781],
    'Longitude': [-74.0060, -118.2437, -87.6298],
    'HotelCount': [50, 30, 70]
}

# Create a GeoDataFrame from the data
gdf = gpd.GeoDataFrame(city_data, geometry=gpd.points_from_xy(city_data['Longitude'], city_data['Latitude']))

# Plot the map
world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
ax = world.plot(color='lightgray', edgecolor='black', figsize=(10, 6))

# Plot hotels on top of the map
gdf.plot(ax=ax, color='red', marker='o', markersize=gdf['HotelCount'], alpha=0.7, legend=True)

# Add labels for each city
for x, y, label in zip(gdf.geometry.x, gdf.geometry.y, gdf['City']):
    ax.text(x, y, label, fontsize=8, ha='right')

# Add legend and title
plt.legend(['Hotels'])
plt.title('Hotel Distribution in Cities')

# Show the plot
plt.show()

In [ ]:
!pip install folium

In [40]:
import folium
from folium.plugins import MarkerCluster

# Hypothetical data - Replace this with your actual data
city_data = {
    'City': ['City A', 'City B', 'City C'],
    'Latitude': [40.7128, 34.0522, 41.8781],
    'Longitude': [-74.0060, -118.2437, -87.6298],
    'HotelCount': [50, 30, 70]
}

# Create a Folium map centered around the first city
map_center = [city_data['Latitude'][0], city_data['Longitude'][0]]
my_map = folium.Map(location=map_center, zoom_start=5)

# Create a MarkerCluster layer
marker_cluster = MarkerCluster().add_to(my_map)

# Add markers for each city with hotel count as the radius
for i in range(len(city_data['City'])):
    folium.CircleMarker(
        location=[city_data['Latitude'][i], city_data['Longitude'][i]],
        radius=city_data['HotelCount'][i],
        color='red',
        fill=True,
        fill_color='red',
        fill_opacity=0.7,
        popup=f"{city_data['City'][i]} - {city_data['HotelCount'][i]} hotels"
    ).add_to(marker_cluster)

# Save the map as an HTML file
my_map.save("hotel_density_map.html")

# Open the map in your default web browser
import webbrowser
webbrowser.open("hotel_density_map.html")

True

In [ ]:
# Import the required library
from geopy.geocoders import Nominatim

# Initialize Nominatim API
geolocator = Nominatim(user_agent="MyApp")

location = geolocator.geocode("Paris")

print("The latitude of the location is: ", location.latitude)
print("The longitude of the location is: ", location.longitude)

In [27]:
import folium
from folium.plugins import MarkerCluster
from IPython.display import display

# Hypothetical data - Replace this with your actual data
city_data = {
    'City': ['City A', 'City B', 'City C'],
    'Latitude': [40.7128, 34.0522, 41.8781],
    'Longitude': [-74.0060, -118.2437, -87.6298],
    'HotelCount': [50, 30, 70]
}

# Create a Folium map centered around the first city
map_center = [city_data['Latitude'][0], city_data['Longitude'][0]]
my_map = folium.Map(location=map_center, zoom_start=5)

# Create a MarkerCluster layer
marker_cluster = MarkerCluster().add_to(my_map)

# Add markers for each city with hotel count as the radius
for i in range(len(city_data['City'])):
    folium.CircleMarker(
        location=[city_data['Latitude'][i], city_data['Longitude'][i]],
        radius=city_data['HotelCount'][i],
        color='red',
        fill=True,
        fill_color='red',
        fill_opacity=0.7,
        popup=f"{city_data['City'][i]} - {city_data['HotelCount'][i]} hotels"
    ).add_to(marker_cluster)

# Display the map directly in the notebook
display(my_map)